### PR TITLE
Start orchestration only if enabled and connection is defined

### LINKED ISSUE #27: Stop orchestration if no Vault connection is configured
I guess we should also stop orchestration if no Vault connection is configured.
Otherwise we will cause an error:
```
Failed to push host.example.com data to Vault: ForemanVault::VaultPolicy#policies delegated to vault_connection.policies, but vault_connection is nil:
[...]
```
https://github.com/dm-drogeriemarkt/foreman_vault/blob/586291c29e81b5067d86d218f34d712bb155d8e1/app/models/concerns/foreman_vault/orchestration/vault_policy.rb#L17

### PR DESCRIPTION
**Pull request by laugmanuel**
Fixes #27

### CODE REVIEW

**Comment by laugmanuel** [comment]
> what about the `queue_vault_destroy` action? I think we should also check if the orchestration is enabled there

I also added the check in `queue_vault_destroy`.

**Comment by laugmanuel** [comment]
Rebased on current master after #31 was merged.
Should be ready now @timogoebel , @kamils-iRonin

**Comment by timogoebel** [comment]
Hm. Looks like tests are failing. :-(

**Comment by laugmanuel** [comment]
@timogoebel they should get green now. Setup stuff was missing for the new tests.

**Comment by timogoebel** [comment]
Thanks, @laugmanuel.

**Pull request merged**
